### ISSUE TITLE
rerun sites that don't compute in script

### ISSUE THREAD

**Issue by kjacobsen16** [USGS-WiM/StreamStatsNationalServices#30]
rerun any sites whose basins/characteristics don't compute and rerun after initial multiprocess

**Comment by kjacobsen16** [comment]
@kjacobsen16

**Comment by HansVraga** [comment]
@kjacobsen16 double check the scripts on the server have made their way back to GitHub

**Comment by kjacobsen16** [comment]
done, with last commit
